### ISSUE TITLE
Chinese question generation

### ISSUE THREAD

**Issue by xinsheng44** [andrew-r96/BertQuestionGeneration#3]
Hello, I use this code to solve the problem of Chinese question generation, but the effect is very poor, do you know why

**Comment by andrearosasco** [comment]
This is a bit difficult to figure out without knowing the details :(
What's happening, are you overfitting? Are you using a dataset for question genration or you adapted a question answering one? What hyperparameters did you use?

**Comment by xinsheng44** [comment]
Glad to hear from you. My dataset is a Chinese dataset, and the task is to generate problems. I ran out of the model according to your method, and then I used the model to predict the problem, but the generated Chinese question does not look very good. Can you share your code for generating the problem, because you only have training and evaluation, but no prediction. I'm a new NLP player and I don't know if my request is abrupt. If you can, please send it to my email 772929946@qq.com Thank you very much.

**Comment by andrearosasco** [comment]
I guess the dataset might be the problem. The model takes in input a paragraph of text and an answer and generate a question (like the questions you can find [here](https://rajpurkar.github.io/SQuAD-explorer/explore/1.1/dev/Warsaw.html?model=r-net+%20(ensemble)%20(Microsoft%20Research%20Asia)&version=1.1) for example). It's not designed to generate reasoning or math problems.

To see the generated questions I used to slightly modify the `eval.py` script so I don't have a script ready to send you but it's actually pretty easy. I told a guy how to do that [here](https://github.com/andrew-r96/BertQuestionGeneration/issues/2)
